---
apiVersion: v1
kind: Service
metadata:
  name: tvheadend
  labels:
    app: tvheadend
    name: tvheadend
    tier: service
spec:
  selector:
    name: tvheadend
    tier: tv
  ports:
    - port: 9981
      targetPort: 9981
      name: web
    - port: 9982
      targetPort: 9982
      name: htsp